# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_class_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='attendances',
        ),
        migrations.AlterModelTable(
            name='staffattendance',
            table='staffattendances',
        ),
    ]
