# Generated by Django 6.0.6 on 2026-07-23 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_lecture'),
        ('schools', '0008_ptmmeeting_studentremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topics_covered', models.TextField()),
                ('topics_planned', models.TextField(blank=True, null=True)),
                ('homework_assigned', models.TextField(blank=True, null=True)),
                ('class_behavior', models.CharField(default='Good', max_length=50)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_diaries', to='academics.class')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_diaries', to='schools.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'class_id', 'date')},
            },
        ),
    ]
