# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_lessondiary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='exams',
        ),
        migrations.AlterModelTable(
            name='homework',
            table='homeworks',
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='lectures',
        ),
        migrations.AlterModelTable(
            name='result',
            table='results',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
        migrations.AlterModelTable(
            name='syllabustracking',
            table='syllabustrackings',
        ),
        migrations.AlterModelTable(
            name='timetable',
            table='timetables',
        ),
    ]
