# Generated by Django 6.0.6 on 2026-07-22 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_student_board_student_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyattendanceqr',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyattendanceqr',
            name='school',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='DailyAttendanceQR',
        ),
    ]
