const express = require('express');
const router = express.Router();

const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const studentRoutes = require('./studentRoutes');
const teacherRoutes = require('./teacherRoutes');
const classRoutes = require('./classRoutes');
const subjectRoutes = require('./subjectRoutes');
const attendanceRoutes = require('./attendanceRoutes');
const feeRoutes = require('./feeRoutes');
const examRoutes = require('./examRoutes');
const homeworkRoutes = require('./homeworkRoutes');
const resultRoutes = require('./resultRoutes');
const courseRoutes = require('./courseRoutes');
const lectureRoutes = require('./lectureRoutes');
const notificationRoutes = require('./notificationRoutes');
const timetableRoutes = require('./timetableRoutes');
const busRoutes = require('./busRoutes');
const hostelRoomRoutes = require('./hostelRoomRoutes');
const bookRoutes = require('./bookRoutes');
const inventoryRoutes = require('./inventoryRoutes');
const eventRoutes = require('./eventRoutes');
const certificateRoutes = require('./certificateRoutes');
const subscriptionRoutes = require('./subscriptionRoutes');
const adminRoutes = require('./adminRoutes');
const superAdminRoutes = require('./superAdminRoutes');
const principalRoutes = require('./principalRoutes');
const leaveRoutes = require('./leaveRoutes');
const complaintRoutes = require('./complaintRoutes');
const accountantRoutes = require('./accountantRoutes');
const parentRoutes = require('./parentRoutes');
// API routes mapping
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/students', studentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/classes', classRoutes);
router.use('/subjects', subjectRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/fees', feeRoutes);
router.use('/exams', examRoutes);
router.use('/homeworks', homeworkRoutes);
router.use('/results', resultRoutes);
router.use('/courses', courseRoutes);
router.use('/lectures', lectureRoutes);
router.use('/notifications', notificationRoutes);
router.use('/timetables', timetableRoutes);
router.use('/buses', busRoutes);
router.use('/hostel-rooms', hostelRoomRoutes);
router.use('/books', bookRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/events', eventRoutes);
router.use('/certificates', certificateRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/admin', adminRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/principal', principalRoutes);
router.use('/leaves', leaveRoutes);
router.use('/complaints', complaintRoutes);
router.use('/profile-updates', require('./profileUpdateRoutes'));
router.use('/school-admin', require('./schoolAdminRoutes'));
router.use('/teacher-portal', require('./teacherPortalRoutes'));
router.use('/accountant', accountantRoutes);
router.use('/admission', require('./admission'));
router.use('/parent', parentRoutes);

module.exports = router;
