# Generated by Django 6.0.6 on 2026-07-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_dailyattendanceqr_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='school',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='school',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user',
        ),
        migrations.RemoveField(
            model_name='principaltask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='principaltask',
            name='school',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='PrincipalTask',
        ),
    ]
