# Generated by Django 6.0.6 on 2026-07-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('attendance', '0002_alter_attendance_class_id'),
        ('finance', '0003_alter_feestructure_class_id'),
        ('schools', '0006_remove_grievance_school_remove_leave_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.class'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='syllabustracking',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='admissionrequest',
            name='class_applied_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='school',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='syllabustracking',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='syllabustracking',
            name='school',
        ),
        migrations.RemoveField(
            model_name='syllabustracking',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='school',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SyllabusTracking',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
