# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_accountant_hostelwarden_hrmanager_librarian_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountant',
            table='accountants',
        ),
        migrations.AlterModelTable(
            name='admissionrequest',
            table='admission_requests',
        ),
        migrations.AlterModelTable(
            name='disciplinelog',
            table='discipline_logs',
        ),
        migrations.AlterModelTable(
            name='hostelwarden',
            table='hostel_wardens',
        ),
        migrations.AlterModelTable(
            name='hrmanager',
            table='hr_managers',
        ),
        migrations.AlterModelTable(
            name='librarian',
            table='librarians',
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parents',
        ),
        migrations.AlterModelTable(
            name='principal',
            table='principals',
        ),
        migrations.AlterModelTable(
            name='ptmmeeting',
            table='ptm_meetings',
        ),
        migrations.AlterModelTable(
            name='receptionist',
            table='receptionists',
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='studentremark',
            table='student_remarks',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
        migrations.AlterModelTable(
            name='transportmanager',
            table='transport_managers',
        ),
    ]
