# Generated by Django 6.0.6 on 2026-07-22 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0005_alter_dailyattendanceqr_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(default=40)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='schools.school')),
            ],
        ),
    ]
