# Generated by Django 6.0.6 on 2026-07-23 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_remove_subject_class_id_alter_student_class_id_and_more'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=255)),
                ('bus_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_routes', to='schools.school')),
            ],
        ),
    ]
