# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_transportroute'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bus',
            table='buses',
        ),
        migrations.AlterModelTable(
            name='transportroute',
            table='transportroutes',
        ),
    ]
