# Generated by Django 6.0.6 on 2026-07-22 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('finance', '0002_remove_expense_vendor_id_payroll_scholarshipdiscount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.class'),
        ),
    ]
