# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_crmsubscriptionrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crmsubscriptionrecord',
            table='crmsubscriptionrecords',
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
        migrations.AlterModelTable(
            name='feereceipt',
            table='feereceipts',
        ),
        migrations.AlterModelTable(
            name='feestructure',
            table='feestructures',
        ),
        migrations.AlterModelTable(
            name='legacyfee',
            table='legacyfees',
        ),
        migrations.AlterModelTable(
            name='payroll',
            table='payrolls',
        ),
        migrations.AlterModelTable(
            name='scholarshipdiscount',
            table='scholarshipdiscounts',
        ),
        migrations.AlterModelTable(
            name='studentfeeinvoice',
            table='studentfeeinvoices',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendors',
        ),
        migrations.AlterModelTable(
            name='vendorpayment',
            table='vendorpayments',
        ),
    ]
