# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='grievance',
            table='grievances',
        ),
        migrations.AlterModelTable(
            name='leave',
            table='school_admin_leaves',
        ),
    ]
