# Generated by Django 6.0.6 on 2026-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_principaltask_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principaltask',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
