# Generated by Django 6.0.6 on 2026-08-08 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_principaltask_assigned_to'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='principaltask',
            table='tasks',
        ),
    ]
