# Generated by Django 6.0.6 on 2026-07-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profileupdaterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='profileupdaterequest',
            table='profile_update_requests',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
